### ISSUE TITLE
Add todo status

### ISSUE THREAD

**Issue by ronantuantvt2** [truongquangloi/react-todo#4]
- [x] Add todo status: To do, In progress, Done, Cancel
- [x] Handle change todo status

**Comment by truongquangloi** [comment]
![image](https://user-images.githubusercontent.com/26532049/50678607-19df8900-1032-11e9-925b-4d7eaf09e2f0.png)

@ronantuantvt2  sao e post commit này lên ko dc anh ?

**Comment by ronantuantvt2** [comment]
@truongquangloi Anh có push 1 commit lên master, giờ em phải pull về trước rồi mới push được
